apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-manager
  namespace: benchmark-web
  labels:
    app: benchmark-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-manager
  template:
    metadata:
      labels:
        app: benchmark-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: NotIn
                    values:
                      - "gpu"
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: benchmark-manager
        image: ghcr.io/yunjae-park1111/manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: benchmark-shared-secrets
              key: MONGO_URL
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: benchmark-shared-secrets
              key: GITHUB_TOKEN
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-manager
  namespace: benchmark-web
  labels:
    app: benchmark-manager
spec:
  selector:
    app: benchmark-manager
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  type: LoadBalancer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: benchmark-manager-config
  namespace: benchmark-web
data:
  DEFAULT_CONFIG_FOLDER: "config"
  DEFAULT_JOB_FOLDER: "job"
  DEFAULT_POLLING_INTERVAL: "180"