apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-results
  namespace: benchmark-web
  labels:
    app: benchmark-results
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark-results
  template:
    metadata:
      labels:
        app: benchmark-results
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: NotIn
                    values:
                      - "gpu"
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: benchmark-results
        image: ghcr.io/yunjae-park1111/results:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: benchmark-shared-secrets
              key: MONGO_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30

---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-results
  namespace: benchmark-web
  labels:
    app: benchmark-results
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: benchmark-results