apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmark-frontend
  namespace: benchmark-web
  labels:
    app: benchmark-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: benchmark-frontend
  template:
    metadata:
      labels:
        app: benchmark-frontend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: NotIn
                    values:
                      - "gpu"
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: benchmark-frontend
        image: ghcr.io/yunjae-park1111/vllm-frontend-public:v1.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-frontend
  namespace: benchmark-web
  labels:
    app: benchmark-frontend
spec:
  selector:
    app: benchmark-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer