apiVersion: v1
kind: Secret
metadata:
  name: benchmark-shared-secrets
  namespace: benchmark-web
type: Opaque
stringData:
  # Base64 encoded MongoDB URL
  # To set: echo -n "mongodb://admin:password123@mongo-service:27017/?replicaSet=rs0&authSource=admin" | base64
  MONGO_URL: ""
  
  # Base64 encoded GitHub token  
  # To set: echo -n "your_github_token_here" | base64
  GITHUB_TOKEN: ""