# MongoDB Secrets Configuration
# Apply this file before deploying the MongoDB cluster

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: benchmark-web
type: Opaque
stringData:
  # MongoDB root password (plain text, no base64 encoding needed)
  mongodb-root-password: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-keyfile
  namespace: benchmark-web
type: Opaque
stringData:
  # MongoDB replica set keyfile for internal authentication
  # This should be a random string of at least 6 characters
  mongodb.key: ""

---
# Usage:
# 1. Apply secrets first:
#    kubectl apply -f mongo-secrets.yaml
#
# 2. Then deploy MongoDB cluster:
#    kubectl apply -f mongo-cluster.yaml 