replicaCount: 2

image:
  repository: yidadaa/chatgpt-next-web
  pullPolicy: IfNotPresent
  tag: "v2.15.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "nextchat"

serviceAccount:
  create: true
  annotations: {}
  name: "nextchat-sa"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  name: "nextchat"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: chat.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nextchat-tls
      hosts:
        - chat.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - nextchat
        topologyKey: kubernetes.io/hostname

# NextChat specific configurations for vLLM integration
nextchat:
  # vLLM Service URL as per PRD
  baseUrl: "http://vllm:8000"
  openaiApiKey: "sk-proxy"
  defaultModel: "qwen3-8b"

  # Security configurations
  code: ""
  hideUserApiKey: true
  disableGpt4: false
  enableBalance: false
  disableFastLink: false

  # Custom configurations
  customDomain: "chat.example.com"
  buildMode: "standalone"

  # Model configurations
  customModels: "qwen3-8b"
  customApiEndpoint: "http://vllm:8000"

env:
  - name: BASE_URL
    value: "http://vllm:8000"
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: nextchat-secrets
        key: openai-api-key
  - name: DEFAULT_MODEL
    value: "qwen3-8b"
  - name: CUSTOM_MODELS
    value: "qwen3-8b"
  - name: HIDE_USER_API_KEY
    value: "1"
  - name: DISABLE_GPT4
    value: "1"
  - name: HOSTNAME
    value: "0.0.0.0"

secrets:
  enabled: true
  name: "nextchat-secrets"
  data:
    openai-api-key: "sk-proxy"

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""
  mountPath: /app/data

# Health checks
livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
