apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: vllm-nextchat
  source:
    repoURL: https://github.com/thakicloud/vllm-manifests-public.git
    path: nginx-ingress
    targetRevision: HEAD
    directory:
      exclude: "ingress-argocd.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true