apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vllm-nextchat
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/thakicloud/vllm-manifests-public.git'
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: vllm-nextchat
    server: https://kubernetes.default.svc
  - namespace: nginx-ingress
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: v1
kind: Secret
metadata:
  name: vllm-nextchat-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: vllm-nextchat
  project: vllm-nextchat
  url: https://github.com/thakicloud/vllm-manifests-public.git
  type: git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    
    -----END OPENSSH PRIVATE KEY-----