apiVersion: v2
name: vllm
description: A Helm chart for vLLM inference server
type: application
version: 0.1.0
appVersion: "v0.5.0"
keywords:
  - vllm
  - llm
  - inference
  - ai
  - gpu
home: https://github.com/your-org/vllm-nextchat
sources:
  - https://github.com/vllm-project/vllm
maintainers:
  - name: platform-team
    email: platform@your-org.com
