apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  description: Project for the VLLM frontend application
  sourceRepos:
  - 'https://github.com/thakicloud/vllm-manifests-public.git'
  destinations:
  - namespace: nginx-ingress
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: nginx-ingress
  source:
    repoURL: https://github.com/thakicloud/vllm-manifests-public.git
    path: nginx-ingress
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 