apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-forwarding
  # This ConfigMap must be in the same namespace as your NGINX Ingress controller.
  # 'ingress-nginx' is a common default namespace.
  namespace: nginx-ingress
data:
  "10000": "vllm-nextchat/model-benchmark-frontend-svc:80"
  "10001": "vllm-nextchat/vllm:8000"
  "10002": "vllm-nextchat/nextchat:3000" 

  "10010": "argocd/argocd-server:443"
  "10011": "vllm-nextchat/grafana:3000"