---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: vllm-nextchat
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      isDefault: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: vllm-nextchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-admin
              key: password
        volumeMounts:
        - name: datasource
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboard-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards
          mountPath: /var/lib/grafana/dashboards
        - name: storage
          mountPath: /var/lib/grafana
      volumes:
      - name: datasource
        configMap:
          name: grafana-datasource
      - name: dashboard-config
        configMap:
          name: grafana-dashboard-config
      - name: dashboards
        configMap:
          name: vllm-gpu-dashboard
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: vllm-nextchat
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: grafana-admin
#   namespace: vllm-nextchat
#   labels:
#     app.kubernetes.io/name: grafana
#     app.kubernetes.io/component: security
# stringData:
#   password: "init-password" 