apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-benchmark-frontend
  labels:
    app: model-benchmark-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-benchmark-frontend
  template:
    metadata:
      labels:
        app: model-benchmark-frontend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: model-benchmark-frontend
        image: ghcr.io/thakicloud/vllm-frontend-public:v1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: model-benchmark-frontend-svc
spec:
  selector:
    app: model-benchmark-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP