apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vllm-nextchat
  namespace: argocd
spec:
  description: Project for the VLLM NextChat application
  sourceRepos:
  - 'https://github.com/thakicloud/vllm-manifests-public.git'
  destinations:
  - namespace: vllm-nextchat
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-nextchat
  namespace: argocd
spec:
  project: vllm-nextchat
  source:
    repoURL: 'https://github.com/thakicloud/vllm-manifests-public.git'
    targetRevision: HEAD
    path: vllm-nextchat
    helm:
      valueFiles:
      - custom-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vllm-nextchat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 