apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextchat.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextchat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nextchat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nextchat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextchat.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.secrets.enabled }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: openai-api-key
            {{- end }}
            {{- if .Values.nextchat.baseUrl }}
            - name: BASE_URL
              value: {{ .Values.nextchat.baseUrl | quote }}
            {{- end }}
            {{- if .Values.nextchat.defaultModel }}
            - name: DEFAULT_MODEL
              value: {{ .Values.nextchat.defaultModel | quote }}
            {{- end }}
            {{- if .Values.nextchat.hideUserApiKey }}
            - name: HIDE_USER_API_KEY
              value: "1"
            {{- end }}
            {{- if .Values.nextchat.disableGpt4 }}
            - name: DISABLE_GPT4
              value: "1"
            {{- end }}
            {{- if .Values.nextchat.customModels }}
            - name: CUSTOM_MODELS
              value: {{ .Values.nextchat.customModels | quote }}
            {{- end }}
            {{- if .Values.nextchat.code }}
            - name: CODE
              value: {{ .Values.nextchat.code | quote }}
            {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "nextchat.fullname" . }}-data
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}