{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
{{- if .Values.modelCache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vllm.fullname" . }}-model-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.modelCache.storageClass }}
  storageClassName: {{ .Values.modelCache.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.modelCache.size }}
{{- end }}